1. Import the numpy package under the name `np` and print the numpy version.


In [9]:
import numpy as np
print(np.__version__)

1.21.5


2. How to find the memory size of any array.

In [10]:
x = np.array([100,20,34,100,22,445,555])
print("Memory size of one array element in bytes: ",
      x.itemsize)

Memory size of one array element in bytes:  4


3. Create a vector with values ranging from 15 to 25.

In [12]:
v = np.arange(15,26)
print(v)

[15 16 17 18 19 20 21 22 23 24 25]


4. Reverse a vector.

In [13]:
print(v[::-1])

[25 24 23 22 21 20 19 18 17 16 15]


5. Find indices of non-zero elements from [9,4,0,0,4,5].

In [23]:
arr1 = np.array([9,4,0,0,4,5])
my_list = []
for i in range(0,len(arr1)):
    if arr[i] == 0 :
        my_list.append(i)
print(my_list)

[2, 3]


6. Create a 10x10 array with random values and find the minimum and maximum values.

In [39]:
matrix = np.random.rand(10,10)*100
print(matrix)
max = matrix.max()
print('max is ' , max)
min = matrix.min()
print('min is ' , min)

[[84.86134247 83.45244834 20.7167754  31.6986776   2.61709448 78.37308705
  33.20076866 82.45418393 45.85217082 26.21190505]
 [75.62967718 14.90479659 47.4922064  69.32657683 58.1856821  24.25256361
  76.33592239 91.41071597 56.77981548  2.6278164 ]
 [59.20096735 19.06582065 45.51212711 29.00957409 86.25755642 22.18948396
  92.99760115 80.86590697  7.58726014 75.74485106]
 [71.37417162 42.85751057 49.65343011 32.37628053 87.0656791   1.39671653
   1.09588125 49.46714863 84.07022351 84.05853328]
 [45.22186717 45.49936413 93.79961579 83.17025771 55.80935366 63.85442358
  57.57024711 14.83169493  1.20815741 39.69295217]
 [12.69036544 61.36012725 10.69346764 28.09750813 34.65128659 63.51341651
  40.04171233 10.78294657 33.45563371 31.05025373]
 [12.63741546 21.1869107  97.69044252  8.95999663 37.639837   94.32994455
   4.91203228 27.23682526 10.32542871 40.97921064]
 [60.94129496 50.81427429  7.02207977 88.36647009 17.77963342 69.71836706
  54.42992583 85.32684004 81.30603166 12.72475895]


In [36]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.84678396 0.36094434 0.29616111 0.95567767 0.19410474]
 [0.41493818 0.37876862 0.96602032 0.11684303 0.24319752]
 [0.03889371 0.53609716 0.17964508 0.99137992 0.98179593]
 [0.82739754 0.06524686 0.53585006 0.31963566 0.27891232]
 [0.53094603 0.56715186 0.83371499 0.24935418 0.17942383]]
After normalization:
[[0.84819102 0.3381158  0.27010092 0.96251679 0.16295357]
 [0.39480306 0.35682922 0.97337536 0.08183775 0.2144953 ]
 [0.         0.52200594 0.14777261 1.         0.98993792]
 [0.82783753 0.02766775 0.5217465  0.29474648 0.25199169]
 [0.51659785 0.55460976 0.83447012 0.22095908 0.14754033]]
