1. Import the numpy package under the name `np` and print the numpy version.


In [116]:
from sklearn import preprocessing
import numpy as np
print(np.__version__)

1.21.5


2. How to find the memory size of any array.

In [103]:
x = np.array([100,20,34,100,22,445,555])
print("Memory size of one array element in bytes: ",
      x.itemsize)

Memory size of one array element in bytes:  4


3. Create a vector with values ranging from 15 to 25.

In [104]:
v = np.arange(15,26)
print(v)

[15 16 17 18 19 20 21 22 23 24 25]


4. Reverse a vector.

In [105]:
print(v[::-1]) # [::-1] will reverse the list

[25 24 23 22 21 20 19 18 17 16 15]


5. Find indices of non-zero elements from [9,4,0,0,4,5].

In [106]:
arr = np.array([9,4,0,0,4,5])
my_list = [] # make a empty list, iterate array, if number not equal to zero, append to list
for i in range(0,len(arr)):
    if arr[i] != 0 :
        my_list.append(i)
print(my_list)

[0, 1, 4, 5]


6. Create a 10x10 array with random values and find the minimum and maximum values.

In [107]:
array = np.random.randint(100, size=(100)) # this create 100 random number, number range from 0 to 99
matrix = array.reshape(10, 10) # .reshape method can reshape a list of 100 number into 10 by 10 matrix
print(matrix)
max = matrix.max()
print('max is ' , max)
min = matrix.min()
print('min is ' , min)


[[78 14 34 80  4 72 99 81 67 74]
 [10 28  4 45 55 80 89 30 47  6]
 [62 70  1 73 27  2 11 20 12 87]
 [31  1 15 64 49 27 21 15 71 57]
 [19  9 73 74 82 74 85 72 79 55]
 [92 31 43 18 85 38 89 86  9 37]
 [46 46  5 64 31 84 40 33 38 49]
 [67 25 10 70 93 83 43 63 42 72]
 [68 71 97 18 34 72 81 12 51 13]
 [34 50 39  5 28 21 58 17 45 41]]
max is  99
min is  1


7. Normalize a 5x5 random matrix.

### *Formula for Normalize*  $$x_{new} = \frac{x - x_{min}}{x_{max}-x_{min}}$$

In [115]:
array = np.random.randint(11, size=(25)) #generate 5 by 5 matrix, with random number between 0 to 10
x = array.reshape(5, 5)
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min() # find min and max number out of matrix
print(xmax,xmin)
x = (x - xmin)/(xmax - xmin) # use formula difference between min and number / difference between max and min
print("After normalization:")
print(x)

Original Array:
[[ 8  5  8  1  0]
 [ 2  7  6  8 10]
 [ 5  8  5  3  9]
 [ 9  3  3  2  0]
 [ 0  3  7  1  9]]
10 0
After normalization:
[[0.8 0.5 0.8 0.1 0. ]
 [0.2 0.7 0.6 0.8 1. ]
 [0.5 0.8 0.5 0.3 0.9]
 [0.9 0.3 0.3 0.2 0. ]
 [0.  0.3 0.7 0.1 0.9]]


In [119]:
array = np.random.randint(11, size=(25)) #generate 5 by 5 matrix, with random number between 0 to 10
x = array.reshape(5, 5)
print(x)
normalized_arr = preprocessing.normalize([x])
print(normalized_arr)

[[1 1 0 6 3]
 [1 7 0 4 1]
 [2 8 1 1 5]
 [9 5 1 0 5]
 [5 9 7 5 0]]


ValueError: Found array with dim 3. the normalize function expected <= 2.

8. Multiply a 5x3 matrix by a 3x2 matrix.

In [94]:
array = np.random.randint(10, size=(15))
arr1 = array.reshape(5, 3)
print(arr1)


array = np.random.randint(10, size=(6))
arr2 = array.reshape(3, 2)
print(arr2)


print(np.matmul(arr1,arr2))


[[2 2 4]
 [6 9 0]
 [2 7 8]
 [4 0 2]
 [2 9 6]]
[[6 2]
 [5 9]
 [2 2]]
[[30 30]
 [81 93]
 [63 83]
 [28 12]
 [69 97]]


9. Create random vector of size 10 and replace the maximum value by 0.

In [91]:
array = np.random.randint(50,size = (10)) # generate 10 random number between 0 to 49
print("Original array:")
print(array)

print('max number is: ',array.max()) # .argmax will returns the indices of the maximum values, then set to 0
array[array.argmax()] = 0

print("Maximum value replaced by 0:")
print(array)

Original array:
[17 19 25 36  9 28 14 28 46 32]
max number is:  46
Maximum value replaced by 0:
[17 19 25 36  9 28 14 28  0 32]


10. Create a null vector of size 10 but the fifth value which is 1.

In [92]:
null_vector = np.zeros(10) # generate empty list with size 10
null_vector[4] = 1 # fifth value which has indices of 4, set to 1
print(null_vector) # print out list

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
