1. Import the numpy package under the name `np` and print the numpy version.


In [1]:
import numpy as np
print(np.__version__)

1.21.5


2. How to find the memory size of any array.

In [2]:
x = np.array([100,20,34,100,22,445,555])
print("Memory size of one array element in bytes: ",
      x.itemsize)

Memory size of one array element in bytes:  4


3. Create a vector with values ranging from 15 to 25.

In [3]:
v = np.arange(15,26)
print(v)

[15 16 17 18 19 20 21 22 23 24 25]


4. Reverse a vector.

In [4]:
print(v[::-1]) # [::-1] will reverse the list

[25 24 23 22 21 20 19 18 17 16 15]


5. Find indices of non-zero elements from [9,4,0,0,4,5].

In [5]:
arr = np.array([9,4,0,0,4,5])
my_list = [] # make a empty list, iterate array, if number not equal to zero, append to list
for i in range(0,len(arr)):
    if arr[i] != 0 :
        my_list.append(i)
print(my_list)

[0, 1, 4, 5]


6. Create a 10x10 array with random values and find the minimum and maximum values.

In [6]:
array = np.random.randint(100, size=(100)) # this create 100 random number, number range from 0 to 99
matrix = array.reshape(10, 10) # .reshape method can reshape a list of 100 number into 10 by 10 matrix
print(matrix)
max = matrix.max()
print('max is ' , max)
min = matrix.min()
print('min is ' , min)


[[31 39  9 61 31 85 62 70 19 41]
 [75 43 92 87 36  8 12 95 80 93]
 [30 88 50 92 42 46 75 96  4 50]
 [69 98 22 31 18 80 49 83 65 47]
 [44 64 49 17 78 84  0 95 22 50]
 [45 97 84 13 82 25 87 26 23 74]
 [88 37 28 63 34 61 17 82 22 20]
 [54 53 85 21  3 64 22 11 60 39]
 [ 5 38  5 57 10  2 85 26 36 55]
 [21 60 26 47 47 12 22 46 63 33]]
max is  98
min is  0


7. Normalize a 5x5 random matrix.

### *Formula for Normalize*  $$x_{new} = \frac{x - x_{min}}{x_{max}-x_{min}}$$

In [7]:
array = np.random.randint(11, size=(25)) #generate 5 by 5 matrix, with random number between 0 to 10
x = array.reshape(5, 5)
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min() # find min and max number out of matrix
print(xmax,xmin)
x = (x - xmin)/(xmax - xmin) # use formula difference between min and number / difference between max and min
print("After normalization:")
print(x)

Original Array:
[[10  4  4  2  0]
 [ 7  4  1  6  2]
 [ 9  9 10  3  2]
 [ 9 10  8  9  9]
 [ 1  9  2  6 10]]
10 0
After normalization:
[[1.  0.4 0.4 0.2 0. ]
 [0.7 0.4 0.1 0.6 0.2]
 [0.9 0.9 1.  0.3 0.2]
 [0.9 1.  0.8 0.9 0.9]
 [0.1 0.9 0.2 0.6 1. ]]


8. Multiply a 5x3 matrix by a 3x2 matrix.

In [8]:
array = np.random.randint(10, size=(15))
arr1 = array.reshape(5, 3)
print(arr1)


array = np.random.randint(10, size=(6))
arr2 = array.reshape(3, 2)
print(arr2)


print(np.matmul(arr1,arr2))


[[0 7 2]
 [6 0 7]
 [9 8 2]
 [5 3 3]
 [2 8 1]]
[[8 7]
 [9 9]
 [6 9]]
[[ 75  81]
 [ 90 105]
 [156 153]
 [ 85  89]
 [ 94  95]]


9. Create random vector of size 10 and replace the maximum value by 0.

In [9]:
array = np.random.randint(50,size = (10)) # generate 10 random number between 0 to 49
print("Original array:")
print(array)

print('max number is: ',array.max()) # .argmax will returns the indices of the maximum values, then set to 0
array[array.argmax()] = 0

print("Maximum value replaced by 0:")
print(array)

Original array:
[33 27  2 27 47 12 27 25  7 23]
max number is:  47
Maximum value replaced by 0:
[33 27  2 27  0 12 27 25  7 23]


10. Create a null vector of size 10 but the fifth value which is 1.

In [10]:
null_vector = np.zeros(10) # generate empty list with size 10
null_vector[4] = 1 # fifth value which has indices of 4, set to 1
print(null_vector) # print out list

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
