1. Import the numpy package under the name `np` and print the numpy version.


In [83]:
import numpy as np
print(np.__version__)

1.21.5


2. How to find the memory size of any array.

In [84]:
x = np.array([100,20,34,100,22,445,555])
print("Memory size of one array element in bytes: ",
      x.itemsize)

Memory size of one array element in bytes:  4


3. Create a vector with values ranging from 15 to 25.

In [85]:
v = np.arange(15,26)
print(v)

[15 16 17 18 19 20 21 22 23 24 25]


4. Reverse a vector.

In [86]:
print(v[::-1]) # [::-1] will reverse the list

[25 24 23 22 21 20 19 18 17 16 15]


5. Find indices of non-zero elements from [9,4,0,0,4,5].

In [87]:
arr = np.array([9,4,0,0,4,5])
my_list = [] # make a empty list, iterate array, if number not equal to zero, append to list
for i in range(0,len(arr)):
    if arr[i] != 0 :
        my_list.append(i)
print(my_list)

[0, 1, 4, 5]


6. Create a 10x10 array with random values and find the minimum and maximum values.

In [88]:
array = np.random.randint(100, size=(100)) # this create 100 random number, number range from 0 to 99
matrix = array.reshape(10, 10) # .reshape method can reshape a list of 100 number into 10 by 10 matrix
print(matrix)
max = matrix.max()
print('max is ' , max)
min = matrix.min()
print('min is ' , min)


[[12 51 97 12 24 90 39 25 13 18]
 [82 94 17 15 44 38 61 39 45 20]
 [18 32 21 49 54 63 12 55 31 49]
 [71 96 82 43 65 95 69 84 80  4]
 [31 14 48 85 40 61 71 14 42 77]
 [33 40 70 13 43  1 40 11 36 86]
 [91 90 75 77 43 35 45 92  2 29]
 [74 79 79 75 29 51  0  5 87 37]
 [51 36 50 58 81 54 83 34 63  2]
 [51 34 97 74  1  1 88 67 77 77]]
max is  97
min is  0


7. Normalize a 5x5 random matrix.

In [89]:
x= np.random.randint((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[2 3]
After normalization:
[0. 1.]


8. Multiply a 5x3 matrix by a 3x2 matrix.

In [90]:
array = np.random.randint(10, size=(15))
arr1 = array.reshape(5, 3)
print(arr1)


array = np.random.randint(10, size=(6))
arr2 = array.reshape(3, 2)
print(arr2)


print(np.matmul(arr1,arr2))


[[7 8 3]
 [9 6 8]
 [3 4 7]
 [2 8 1]
 [7 2 7]]
[[5 1]
 [2 8]
 [3 2]]
[[60 77]
 [81 73]
 [44 49]
 [29 68]
 [60 37]]


9. Create random vector of size 10 and replace the maximum value by 0.

In [91]:
array = np.random.randint(50,size = (10)) # generate 10 random number between 0 to 49
print("Original array:")
print(array)

print('max number is: ',array.max()) # .argmax will returns the indices of the maximum values, then set to 0
array[array.argmax()] = 0

print("Maximum value replaced by 0:")
print(array)

Original array:
[17 19 25 36  9 28 14 28 46 32]
max number is:  46
Maximum value replaced by 0:
[17 19 25 36  9 28 14 28  0 32]


10. Create a null vector of size 10 but the fifth value which is 1.

In [92]:
null_vector = np.zeros(10) # generate empty list with size 10
null_vector[4] = 1 # fifth value which has indices of 4, set to 1
print(null_vector) # print out list

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
